{
  "message": "AttributeError: module 'tensorflow.keras.metrics' has no attribute 'root_mean_squared_error'",
  "traceback": ["py_get_attr_impl(x, name, silent)", "py_get_attr(x, name)", "py_get_attr_or_item(x, name, TRUE)", "`$.python.builtin.object`(x, name)", "`$.python.builtin.module`(tf$metrics, root_mean_squared_error)", "tf$metrics$root_mean_squared_error", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "tuning_run(\"hitters_hyper.R\", flags = list(nodes = c(16, 32, \n    128), learning_rate = c(0.05, 0.01, 0.001), batch_size = c(50, \n    100), epochs = c(30), activation = c(\"relu\", \"sigmoid\", \"tanh\"), \n    optimizer = \"adam\"), sample = 0.02)"]
}
